# Initial Data Exploration

In this section, I perform a preliminary analysis of the raw sales data to understand its structure, identify inconsistencies, and uncover patterns that will inform the data cleaning and transformation process. We'll inspect key columns such as customer names, invoice numbers, product descriptions, and totals, and assess common issues such as:

- Multi-line entries per invoice
- Inconsistent or ambiguous product labels (e.g., "HD", "High Dense", "N29/200")
- Spelling errors and data formatting issues

In [3]:
import pandas as pd

path = "../data/data.txt"

sales_df = pd.read_csv(path, on_bad_lines= "skip", encoding='cp1252')

/var/folders/qv/nw3vsgqx4kj68b4rlzsgkx540000gn/T/ipykernel_35460/4136353355.py:5: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  sales_df = pd.read_csv(path, on_bad_lines= "skip", encoding='cp1252')

In [4]:
sales_df.head()

,Co./Last Name,Date,Invoice #,First Name,Item Number,Quantity,Description,Price,Total
0,Samantha Thomas,5/04/2025,00006814,NaN,Miscellaneous,1,"2""Outdoor 2 x 1000*1730(Z)",$527.27,$527.27
1,Samantha Thomas,5/04/2025,00006814,NaN,Dacron,2,Dacron,$54.545,$109.09
2,Samantha Thomas,5/04/2025,00006814,NaN,Miscellaneous,4,Sunbrella Payton,$70.91,$283.64
3,Samantha Thomas,5/04/2025,00006814,NaN,Miscellaneous,2.5,Vistaweave,$80.00,$200.00
4,Samantha Thomas,5/04/2025,00006814,NaN,Miscellaneous,2,Covers,$181.82,$363.64

In [7]:
sales_df.sample(n= 10)

,Co./Last Name,Date,Invoice #,First Name,Item Number,Quantity,Description,Price,Total
51297,Ricky Sullivan,29/09/2017,00052685,NaN,Miscellaneous,2,sewing,$63.635,$127.27
57673,James OBRIEN,25/03/2019,00056120,NaN,Miscellaneous,1,1 Baby crib mattress,$72.73,$72.73
53209,An oasis in the City,1/03/2018,00053756,NaN,Miscellaneous,1,2 x 2000 x 660 x 1330 x 75 mm dryflow cut at 4...,$523.64,$523.64
73667,Mad Monkey Backpackers,25/10/2022,2802,NaN,Miscellaneous,2.0,2 meters of vista weave for bases,$163.64,$327.28
60989,Monique Leoung,17/01/2020,00057793,NaN,Miscellaneous,1,2035mm X 765mm X 50mm 29/400 Charcoal,$116.36,$116.36
75883,Michelle Stewart,23/05/2023,3840,NaN,Miscellaneous,1.0,"Length 133cm, Width 52cm x 50 mm MD",$36.36,$36.36
45042,"McCallum, Andrew",15/04/2016,00049575,NaN,Miscellaneous,1,1 meter noosa shark for small ones x 2,$42.73,$42.73
61877,Jaaims,3/04/2020,00058269,NaN,"2""HD",4,"Piece 2"" 29/200",$0.0077,$36.36
33238,Knifeway,13/11/2013,00043039,NaN,ESR,1,Exercise Sports Roll,$36.36,$36.36
27326,Damien,10/11/2012,00039799,NaN,Acc50/25,"16,728",piece 50/25 Accoustic Foam 82 x 204,$0.009,$150.91

In [19]:
sales_df["Date"] = pd.to_datetime(sales_df["Date"], format="%d/%m/%Y")
sales_df["Invoice #"] = pd.to_numeric(sales_df["Invoice #"], errors="coerce").dropna().astype("int64")

sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83107 entries, 0 to 83106
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Co./Last Name  83107 non-null  object
 1   Date           83107 non-null  datetime64[ns]
 2   Invoice #      83106 non-null  float64
 3   First Name     9760 non-null   object
 4   Item Number    82447 non-null  object
 5   Quantity       83107 non-null  object
 6   Description    82275 non-null  object
 7   Price          83107 non-null  object
 8   Total          83107 non-null  object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 5.7+ MB

In [23]:
sales_df["Item Number"].value_counts()[:15]

Item Number
Miscellaneous    40291
Discount          3009
Covers            1978
4"HD              1915
3"HD              1710
D18               1560
2"HD              1370
3"MD              1165
4"MD              1090
2"MD              1081
D25                924
Delivery           907
D35                899
5"HD               677
BSb                671
Name: count, dtype: int64